// Copyright 2024-present Niobium Microsystems, Inc.
// Licensed under the Apache License, Version 2.0.
//
// Bootstrap example — server side
//
// Loads the CKKS crypto context, keys, and ciphertext generated by client.cpp.
// Records the bootstrapping operation via the Niobium compiler, producing
// a FHETCH instruction trace. Serializes the result ciphertext for the
// decrypt step.
//
// Usage: ./bootstrap_server [key_dir]

#include "openfhe.h"
#include "niobium/compiler.h"

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

using namespace lbcrypto;

int main(int argc, char* argv[]) {
    // ---- Niobium compiler setup ----
    niobium::compiler().init(argc, argv);
    niobium::compiler().set_program_info(
        "bootstrap_server", "1.0",
        "CKKS bootstrapping — FHETCH trace recording");
    niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);

    niobium::Compiler::CacheParameters params;
    params.push_back({"workload", "ckks_bootstrap"});
    niobium::compiler().cache_parameters(params);

    std::string keyDir = "bootstrap_keys";
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg.find("--") != 0) {
            keyDir = arg;
            break;
        }
    }

    std::cout << "=== CKKS Bootstrap — Server (Trace Recording) ===" << std::endl;
    std::cout << "Loading keys from: " << keyDir << std::endl;

    // ---- Load crypto context ----
    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(keyDir + "/cc.bin", cc, SerType::BINARY))
        throw std::runtime_error("Failed to load crypto context");

    usint ringDim = cc->GetRingDimension();
    std::cout << "Ring dimension: " << ringDim << std::endl;

    // ---- Load keys ----
    std::cout << "Loading eval mult key..." << std::endl;
    {
        std::ifstream mkStream(keyDir + "/mk.bin", std::ios::in | std::ios::binary);
        if (!mkStream.is_open() || !cc->DeserializeEvalMultKey(mkStream, SerType::BINARY))
            throw std::runtime_error("Failed to load eval mult key");
    }

    std::cout << "Loading eval automorphism keys..." << std::endl;
    {
        std::ifstream rkStream(keyDir + "/rk.bin", std::ios::in | std::ios::binary);
        if (!rkStream.is_open() || !cc->DeserializeEvalAutomorphismKey(rkStream, SerType::BINARY))
            throw std::runtime_error("Failed to load eval automorphism keys");
    }

    // ---- Load ciphertext ----
    Ciphertext<DCRTPoly> ciph;
    if (!Serial::DeserializeFromFile(keyDir + "/ciphertext.bin", ciph, SerType::BINARY))
        throw std::runtime_error("Failed to load ciphertext");

    // ---- Bootstrap precomputation ----
    std::vector<uint32_t> levelBudget = {4, 4};
    cc->EvalBootstrapSetup(levelBudget);

    // ---- Capture crypto context for the Niobium compiler ----
    niobium::compiler().capture_crypto_context(cc);

    // ---- Tag the input ciphertext ----
    niobium::compiler().tag_input("input_cipher", ciph);

    Ciphertext<DCRTPoly> ciphertextAfter;

    if (!niobium::compiler().is_cache_valid()) {
        // ---- RECORDING PHASE (hollow mode) ----
        // Hollow mode skips expensive polynomial math during recording
        // while preserving structure and firing probes correctly.
        // This reduces bootstrap recording time from minutes to seconds.
        // The result ciphertext is NOT valid after hollow recording —
        // real results come from the Niobium hardware after compilation.
        std::cout << "\n--- Recording bootstrap operation (hollow mode) ---" << std::endl;
        niobium::compiler().enable_hollow_mode(true);
        niobium::compiler().start();

        ciphertextAfter = cc->EvalBootstrap(ciph);

        niobium::compiler().probe("output_cipher", ciphertextAfter);
        niobium::compiler().stop();
        niobium::compiler().enable_hollow_mode(false);
        std::cout << "Recording complete. FHETCH trace written." << std::endl;
        std::cout << "NOTE: Hollow mode was used — result ciphertext is not valid." << std::endl;
        std::cout << "      In production, the Niobium server returns the real result" << std::endl;
        std::cout << "      after compiling and executing the trace on hardware." << std::endl;
    } else {
        std::cout << "\n--- Using cached trace ---" << std::endl;
    }

    // In a real deployment, the FHETCH trace + serialized inputs would be
    // sent to the Niobium compilation service. The server would return the
    // hardware-computed result ciphertext, which the client then decrypts.
    //
    // For this example, no ct_result.bin is produced since hollow mode
    // does not compute real polynomial values.

    return 0;
}
