#!/bin/bash
# ============================================================================
# fhetch_server.sh — start nbcc_fhetch_replay_server wired to a compiler build
#
# Resolves the paths a deployment normally has to handcraft:
#   - LD_LIBRARY_PATH for OpenFHE + libnbcc + NTL
#   - --exec path to the compiler-side nbcc_fhetch_replay
#
# Foreground by default. Override PORT / BIND / NIOBIUM_COMPILER_ROOT via env.
# Additional args after "--" go straight through to the server.
#
# Example:
#   NIOBIUM_COMPILER_ROOT=$HOME/niobium-compiler \
#     scripts/fhetch_server.sh
#
#   PORT=19443 scripts/fhetch_server.sh -- --bind 0.0.0.0
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
CLIENT_ROOT="$(cd "$HERE/.." && pwd)"

# Default: compiler lives two levels up from the client (the submodule layout
# of niobium-compiler). Override NIOBIUM_COMPILER_ROOT for anything else.
: "${NIOBIUM_COMPILER_ROOT:=$(cd "$CLIENT_ROOT/../.." && pwd)}"

# Build dir used by the compiler's top-level Makefile. Debug uses dbuild/.
: "${NIOBIUM_COMPILER_BUILD:=$NIOBIUM_COMPILER_ROOT/build}"

: "${PORT:=9443}"
: "${BIND:=127.0.0.1}"

SERVER_BIN="$CLIENT_ROOT/build/src/fhetch_transport/nbcc_fhetch_replay_server"
COMPILER_BIN="$NIOBIUM_COMPILER_BUILD/nbcc_fhetch_replay"

# niobium_client.env (written by `make config-client-release`) records the
# OpenFHE install dir the build was linked against. See test_transport_mult.sh
# for the full rationale.
ENV_FILE="$CLIENT_ROOT/build/niobium_client.env"
[[ -f "$ENV_FILE" ]] && . "$ENV_FILE"
: "${OPENFHE_LIB:=$CLIENT_ROOT/vendor/lib/openfhe/lib}"
NTL_LIB="$NIOBIUM_COMPILER_ROOT/deps/photovoltaic/build/ntl/lib"

for path in "$SERVER_BIN" "$COMPILER_BIN"; do
  if [[ ! -x "$path" ]]; then
    echo "error: not executable: $path" >&2
    exit 2
  fi
done

# The server is one of our binaries and needs our OpenFHE on the loader path.
# But it spawns the compiler's replay binary as a child for every request, and
# a child inherits this environment — where an inherited search path takes
# precedence over the rpath the replay binary uses to find the OpenFHE it was
# built against. The two are independent builds, so it would load ours instead,
# and whenever the two differ that surfaces as an undefined symbol at startup.
#
# Clearing the path wholesale is not an option here: the two processes need
# *different* paths, not no path. So give the child its own environment rather
# than sharing ours — point --exec at a wrapper that sets the loader path to
# the compiler side only and execs the real binary.
export LD_LIBRARY_PATH="$OPENFHE_LIB:$NIOBIUM_COMPILER_BUILD:$NTL_LIB${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

EXEC_WRAPPER="$CLIENT_ROOT/build/fhetch_replay_exec_wrapper.sh"
cat > "$EXEC_WRAPPER" <<WRAPPER
#!/bin/bash
# Generated by scripts/fhetch_server.sh — do not edit.
# Replaces the inherited loader path with the compiler's own, so the replay
# binary resolves the OpenFHE it was built against rather than the client's.
export LD_LIBRARY_PATH="$NIOBIUM_COMPILER_BUILD:$NTL_LIB"
export DYLD_LIBRARY_PATH="$NIOBIUM_COMPILER_BUILD:$NTL_LIB"
exec "$COMPILER_BIN" "\$@"
WRAPPER
chmod +x "$EXEC_WRAPPER"

echo "[fhetch_server.sh] compiler  = $COMPILER_BIN"
echo "[fhetch_server.sh] server    = $SERVER_BIN"
echo "[fhetch_server.sh] bind/port = $BIND:$PORT"
exec "$SERVER_BIN" --port "$PORT" --bind "$BIND" --exec "$EXEC_WRAPPER" "$@"
