// Copyright 2024-present Niobium Microsystems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ---------------------------------------------------------------------------
// STUB header for the HEIR v2 MLP model entry point `mnist()`.
//
// The real implementation (a ~28K-line rotate/multiply/add forward pass for a
// 784->512->10 MLP, generated by Google's HEIR compiler) and the trained
// weights are NOT vendored in this open-source client. They live in the
// ml-inference submission package — see examples/ml-inference-fhe/HOWTO.md.
//
// This stub lets the example BUILD self-contained (no external/private repo).
// The stubbed mnist() does not perform real inference; to get correct results,
// build against the real submission sources via SUBMISSION_DIR (see Makefile).
// ---------------------------------------------------------------------------
#ifndef MLP_OPENFHE_H_
#define MLP_OPENFHE_H_

#include "openfhe.h"

using namespace lbcrypto;
using CiphertextT = Ciphertext<DCRTPoly>;
using CryptoContextT = CryptoContext<DCRTPoly>;

// 2-layer MLP forward pass. Real signature (matches the HEIR-generated model):
//   v0=fc1_weight, v1=fc1_bias, v2=fc2_weight, v3=fc2_bias, v4=input ciphertext(s).
std::vector<CiphertextT> mnist(CryptoContextT cc,
    std::vector<float> v0, std::vector<float> v1, std::vector<float> v2, std::vector<float> v3,
    std::vector<CiphertextT> v4);

#endif  // ifndef MLP_OPENFHE_H_
